### ISSUE TITLE
Add translation for validation messages

### ISSUE THREAD

**Issue by Jank1310** [Jank1310/datadolphin#55]
Add a english and german description for the different validation messages

**Comment by Flofie** [comment]
würde vorschlagen, dass wir das einfach über den POST zum erstellen des workflows mitgeben
{
"local": "de" / "en"
}

und im workflow bzw. der activity einfach n dictionary mit fallback auf en und den entsprechenden strings.

**Comment by Jank1310** [comment]
Hab i18n schon eingefügt, müssen eigentlich nur die Strings im Frontend ergänzen. Ansonsten wirds schwer bei verschiedenen Sprachen/Personen

**Comment by Flofie** [comment]
ja i18n hab ich gesehen. wie willst du es dann handeln vom backend? soll als message nur der translation key zurückgegeben werden?

**Comment by Jank1310** [comment]
Ich denke wir können über Type schon ziemlich viel machen, oder? Ist die Frage, ob man _message_ da überhaupt noch braucht?

**Comment by Flofie** [comment]
Ich hab mal nen PR verlinkt. Meinst du so?
